DROP TABLE `#__jvoter_contests`;
DROP TABLE `#__jvoter_entries`;
DROP TABLE `#__jvoter_media`;
DROP TABLE `#__jvoter_features`;
DROP TABLE `#__jvoter_plans`;
DROP TABLE `#__jvoter_rating`;
DROP TABLE `#__jvoter_organizations`;
DROP TABLE `#__jvoter_date_orders`;
DROP TABLE `#__jvoter_orders`;